### ISSUE TITLE
About _add_xy_index_channels

### ISSUE THREAD

**Issue by xiaosean** [kashyap7x/Style-Randomization#1]
Is this trick from paper?
I am curious about this effect,
and what is that concept.

```python
    def _add_xy_index_channels(self, img):
        h_s = img.shape[0]
        w_s = img.shape[1]
        c_y_index = np.expand_dims(np.tile(np.arange(h_s),w_s).reshape(w_s,h_s).T,2)/(h_s-1)
        c_x_index = np.tile(np.arange(w_s),h_s).T.reshape(h_s,w_s,1)/(w_s-1)
        img_extended = np.concatenate([img,c_y_index,c_x_index],2).copy()
        return img_extended
```

**Comment by kashyap7x** [comment]
Hi xiaosean,

The idea is to use spatial prior information for segmentation, by adding the relative location in the image as a feature. For example, it is unlikely that pixels of the class 'sky' will be at the bottom of the image or 'road' will be at the top. The idea is discussed in [this paper](https://arxiv.org/abs/1807.03247). In our experiments we only tried adding these spatial features at the final layer, and found it to have no effect.

**Comment by xiaosean** [comment]
@kashyap7x Thank you very much for your kind answer to my question.
I will take a look at this paper,
Thank you!
